### ISSUE TITLE
Keep app open between disconnects / reconnects

### ISSUE THREAD

**Issue by Coolykoen** [bakapear/stadia2xbox#2]
Heya, just wanted to ask if this can be set up to stay open between reconnects?
I want to have it run on startup and just wait for the controller to be plugged in, likewise when i disconnect the controller, i'd like it to wait until i plug it back in.

Would something like that be possible?
Right now i use an autohotkey script that starts the tool whenever it detects any usb device being plugged in, but you can probably tell that's not very efficient haha.

Thanks for your time, 
Koen

**Comment by bakapear** [comment]
This project was just for me to learn a bit of the Go language so I have no further plans on adding features.

I specifically removed listening for devices being plugged in/out because it had a noticable performance impact (At least the method I was trying), so this is just a tool you launch when you need it, instead of having it open and active each time.

Highly recommend you checkout [StadiEm](https://github.com/MWisBest/StadiEm) instead, which supports what you are asking for. 
You'd have to build it from source yourself or if you trust me get a compiled version here: [StadiEm.zip](https://github.com/bakapear/stadia2xbox/files/7838046/StadiEm.zip)

**Comment by Coolykoen** [comment]
Well, for a project just to learn a language, it works very very well. So i was happy with its current state, however, i will indeed check the zip file out for sure, if its just as convenient as yours but also has listening, im sold haha.

Thanks again and yea understandable that you wont consider it ^^
